title: Welcome to my Hello World
author:
	name: Francisco Gálvez
	email: info@iguannaweb.com
description: One.Two.Three.  
show_excerpts: false 
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag